### ISSUE TITLE
setup.py not working properly

### ISSUE THREAD

**Issue by humrochagf** [jochem/Python-EPP#5]
i tried to install the project but on the installation process it gets an error of package not found.

it's because the actual name of the package is 'epp', not 'EPP' which is the name of the module

**Comment by humrochagf** [comment]
i made a pull request that uses `find_packages()` instead of hardcode the package name to prevent this kind of mistakes

**Comment by humrochagf** [comment]
realized just now that there's two others PR`s to this same issue #2 and #4

**Comment by jochem** [comment]
Sorry - I had forgotten about those pull request. Merged this one and closed the other two, thanks!
